export interface KnowledgeNote {
  id: string
  projectId: string | null
  title: string
  categoryPath: string
  filePath: string
  content: string
  autoGenerated: boolean
  tags: string[]
  createdAt: string
  updatedAt: string
}

export interface KnowledgeCategory {
  name: string
  path: string
  children: KnowledgeCategory[]
  notes: KnowledgeNote[]
}
