import { useEffect } from 'react'
import { useKnowledgeStore } from '@/stores/knowledgeStore.ts'
import KnowledgeTree from '@/components/features/knowledge/KnowledgeTree.tsx'
import MarkdownRenderer from '@/components/features/knowledge/MarkdownRenderer.tsx'
import toast from 'react-hot-toast'

export default function KnowledgeBase() {
  const {
    notes,
    filteredNotes,
    currentNote,
    searchQuery,
    loading,
    loadNotes,
    selectNote,
    setSearchQuery,
  } = useKnowledgeStore()

  useEffect(() => {
    loadNotes()
  }, [loadNotes])

  const handleWikilinkClick = (title: string) => {
    const target = notes.find((n) => n.title === title)
    if (target) {
      selectNote(target.id)
    } else {
      toast(`Note "${title}" doesn't exist yet`, { icon: '📝' })
    }
  }

  const handleNewNote = () => {
    toast('Note editor coming soon', { icon: '📝' })
  }

  if (loading) {
    return (
      <div className="font-mono" style={{ padding: '32px 40px', fontSize: 13, color: 'var(--text-tertiary)' }}>
        Loading knowledge base...
      </div>
    )
  }

  return (
    <div style={{ display: 'flex', height: '100%' }}>
      <KnowledgeTree
        notes={filteredNotes}
        selectedNoteId={currentNote?.id ?? null}
        onSelectNote={selectNote}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
        onNewNote={handleNewNote}
      />

      {/* Content area */}
      <div style={{ flex: 1, overflow: 'auto', padding: '24px 36px' }}>
        {currentNote ? (
          <>
            {/* Breadcrumb */}
            <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
              <span className="font-mono" style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>
                {currentNote.filePath}
              </span>
              {currentNote.autoGenerated && (
                <span
                  className="font-mono"
                  style={{
                    marginLeft: 10,
                    fontSize: 10,
                    padding: '2px 8px',
                    borderRadius: 4,
                    backgroundColor: 'var(--bg-tertiary)',
                    color: 'var(--text-tertiary)',
                  }}
                >
                  auto-generated
                </span>
              )}
            </div>

            {/* Markdown content */}
            <MarkdownRenderer
              content={currentNote.content}
              onWikilinkClick={handleWikilinkClick}
            />
          </>
        ) : (
          <div
            className="font-mono"
            style={{
              fontSize: 13,
              color: 'var(--text-tertiary)',
              padding: '80px 0',
              textAlign: 'center',
            }}
          >
            Select a note from the sidebar
          </div>
        )}
      </div>
    </div>
  )
}
