interface NoteBreadcrumbsProps {
  filePath: string
  autoGenerated: boolean
}

export default function NoteBreadcrumbs({ filePath, autoGenerated }: NoteBreadcrumbsProps) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
      <span className="font-mono" style={{ fontSize: 11, color: 'var(--text-tertiary)' }}>
        {filePath}
      </span>
      {autoGenerated && (
        <span
          className="font-mono"
          style={{
            marginLeft: 10,
            fontSize: 10,
            padding: '2px 8px',
            borderRadius: 4,
            backgroundColor: 'var(--bg-tertiary)',
            color: 'var(--text-tertiary)',
          }}
        >
          auto-generated
        </span>
      )}
    </div>
  )
}
